### ISSUE TITLE
If font-family is not found, no text is rendered

### ISSUE THREAD

**Issue by jonoomph** [RazrFalcon/resvg#159]
Hi, this is really more of a question than a bug probably. I am setting up a new Windows 10 build server for OpenShot, and noticed that **resvg.dll** does not render any text. It does in fact render other shapes, gradients, and lines just fine... but anywhere "text" is supposed to be, it renders nothing.

```
git clone https://github.com/RazrFalcon/resvg
cd resvg/capi
QT_DIR="C:\\msys64\\mingw64\\" cargo build --verbose --release --features="qt-backend"
```

I compiled resvg on MSYS2 (using the latest version of **Qt 5.12.4**). No errors were reported during the build. I was also able to link to it with no issues. When OpenShot renders a SVG file though, all text is missing. 

So, just curious if this rings a bell or if this is something silly on my part, missing a dependency, etc... If not, what do you suggest as the best way to troubleshoot an issue like this?  Thank again!

**Comment by RazrFalcon** [comment]
resvg doesn't use backend's text rendering. It uses it's own text layout based on harfbuzz. I guess it can skip text rendering if it could not find any fonts on OS. But it will show warnings in this case. Also, only ttf fonts are supported in 0.7. otf will be supported in 0.8.

In case of Windows, it looks for fonts in `C:\\Windows\\Fonts\\`. I know that at least Travis CI Windows instance has a lot of fonts removed.

**Comment by jonoomph** [comment]
Okay, thanks! I think I see what is happening. I'm trying to use a font which is not found on Windows: **Bitstream Vera Sans**. If I change the font-family to something in the `C:\\Windows\\Fonts\\` directory, it works fine. Seems like it should fall-back on a known font though... I believe that is what `Qt` does, if it cannot find a specified font.

**Comment by RazrFalcon** [comment]
I should fallback. It also should write a warning if it failed. Did you enabled the logging?

**Comment by jonoomph** [comment]
No, we have not enabled logging, but that sounds like a great idea. I'll look into that real quick. Here is the current implementation of resvg in OpenShot: https://github.com/OpenShot/libopenshot/blob/develop/src/QtImageReader.cpp#L82. It's pretty basic currently.

**Comment by jonoomph** [comment]
Related question: If I ship some custom TTF fonts with OpenShot, is there a way to inform resvg of the additional font directory? Or do the font's need to be copied into `C:\\Windows\\Fonts\\`? Thx

**Comment by RazrFalcon** [comment]
No, but it's a good idea. I've opened an issue (#161).

**Comment by jonoomph** [comment]
Here is an example SVG which does not render any text (or fallback) on Windows 10:
[Bar_1.svg.zip](https://github.com/RazrFalcon/resvg/files/3423037/Bar_1.svg.zip). I'm curious if you can reproduce the issue on your side.

**Comment by RazrFalcon** [comment]
Yes, it doesn't work on Windows. Not sure why. On Linux everything is fine. It should fallback to Times New Roman in worst case scenario.

PS: you can use a prebuilt `viewsvg` from Releases to test files.

**Comment by RazrFalcon** [comment]
It works fine on latest master, so I think it was fixed already.

**Comment by jonoomph** [comment]
@RazrFalcon Are you referring to the latest master of resvg or harfbuzz? I will take a look at the prebuilt viewsvg though. Thx

**Comment by RazrFalcon** [comment]
`resvg`. I've just tried to render it using latest version and it worked. Not sure what changed though.

**Comment by jonoomph** [comment]
Okay, nice! I'll update everything and try again. :+1:

**Comment by jonoomph** [comment]
I've tested again with the latest source and dependencies on Windows 10, and I'm still getting no text rendering (when the font is not found). I've enabled logging though, and I'm waiting on some build servers now to catch up. Once that is done, I'll see if any stderr is being output when the fallback rendering fails.

Also, the latest prebuilt binary also fails to render text for me (same conditions: Windows 10 + my test SVG).

**Comment by RazrFalcon** [comment]
Strange. It doesn't work in `viewsvg`, but works in `rendersvg`.

The warning is:

```
Warning (in usvg::convert::text::convert:379): No match for 'asdf234' font-family.
```

Which is expected.

**Comment by RazrFalcon** [comment]
Interesting. It's actually a `ResvgQt.h` bug. I'm querying the default font via Qt and on windows it returns `MS Shell Dlg 2` which is just a dummy that points to an actual font via `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\FontSubstitutes\MS Shell Dlg 2`. In case of Win10 it's Tahoma.

So instead of trying to be smart I will simply use the default `Times New Roman`.

**Comment by jonoomph** [comment]
smart is overrated!
