### ISSUE TITLE
usvg-0.24 from crates.io doesn't compile

### ISSUE THREAD

**Issue by ogoffart** [RazrFalcon/resvg#552]
```
error[E0432]: unresolved import `rustybuzz::ttf_parser`
 --> /home/olivier/.cargo/registry/src/github.com-1ecc6299db9ec823/usvg-0.24.0/src/text/fontdb_ext.rs:8:5
  |
8 | use rustybuzz::ttf_parser;
  |     ^^^^^^^^^^^----------
  |     |          |
  |     |          help: a similar name exists in the module: `text_parser`
  |     no `ttf_parser` in the root

error[E0432]: unresolved import `rustybuzz::ttf_parser`
 --> /home/olivier/.cargo/registry/src/github.com-1ecc6299db9ec823/usvg-0.24.0/src/text/shaper.rs:6:16
  |
6 | use rustybuzz::ttf_parser::GlyphId;
  |                ^^^^^^^^^^ could not find `ttf_parser` in `rustybuzz`
```

ttf_parser export was removed because of https://github.com/RazrFalcon/rustybuzz/issues/59 , but usvg still uses it.
I guess the fix here will be to update the version of rustybuzz to 0.6

**Comment by ogoffart** [comment]
> I guess the fix here will be to update the version of rustybuzz to 0.6

Alternatively, a new release of rustybuzz 0.5.x should be done that restre the `ttf_parser` export (but without bumping the its major version)

**Comment by yisibl** [comment]
I have the same problem.

**Comment by RazrFalcon** [comment]
Yes, this is a known issue. Will be fixed later.

**Comment by liquidnight2** [comment]
I confirm this error. For now, I pin down 0.23.0 for my project.

**Comment by RazrFalcon** [comment]
Should be fixed now.

**Comment by ogoffart** [comment]
It does not apprear to be fixed.  There was no new update to usvg that uses the new rustybuzz,  nor an update to rustybuzz that exports the ttf_parser module.

It appear that the version of rustybuzz that usvg depends on has been yanked. But that doesn't solve the problem: Now, trying to install resvg show this error:

```
$ cargo install resvg
Installing resvg v0.24.0
error: failed to compile `resvg v0.24.0`, intermediate artifacts can be found at `/tmp/cargo-installYIxJDF`

Caused by:
  failed to select a version for the requirement `rustybuzz = "^0.5.2"`
  candidate versions found which didn't match: 0.6.0, 0.5.1, 0.5.0, ...
  location searched: crates.io index
  required by package `usvg v0.24.0`
      ... which satisfies dependency `usvg = "^0.24.0"` of package `resvg v0.24.0`
```

And a similar error happens when trying to use usvg 0.24 or resvg 0.24 as a dependency of another crate in Cargo.toml

**Comment by RazrFalcon** [comment]
I guess version bump is the only choice...
